name: Release windows

on: workflow_dispatch

jobs:
  release:
    name: Build windows binaries
    runs-on: windows-latest
    timeout-minutes: 30

    env:
      AM_DEV_TOKEN: ${{secrets.AM_DEV_TOKEN}}
      LF_API_KEY: ${{secrets.LF_API_KEY}}
      LF_API_SECRET: ${{secrets.LF_API_SECRET}}
      SPOTIFY_DISABLED: 'true'
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install web view dependencies
        run: |
          npm install

      - name: build web view
        run: |
          npm run build:electron

      - name: Install electron dependencies
        run: |
          cd ./app
          npm install

      - name: Install castlabs-evs
        run: python -m pip install --upgrade castlabs-evs

      - name: Authorize castlabs-evs
        run: python -m castlabs_evs.account reauth -A ${{secrets.CASTLABS_ACCOUNT_NAME}} -P ${{secrets.CASTLABS_PASSWORD}}

      - name: Build and package application
        run: |
          npm exec electron-builder --config electron-builder.json --publish always --win
